[versions]
assertj = "3.27.6"
junit = "6.1.0-M1"
lombok = "1.18.42"
slf4j = "2.0.17"
spotless = "8.1.0"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }
jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
